spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      hbm2ddl:
        auto:create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always